apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-woodpecker-token
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: prometheus-openbao
    kind: SecretStore
  target:
    name: prometheus-woodpecker-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: homelab/prometheus
        property: WOODPECKER_PROMETHEUS_AUTH_TOKEN
